#!/usr/bin/env python3

# taken from http://www.piware.de/2011/01/creating-an-https-server-in-python/
# via https://gist.github.com/dergachev/7028596 and 2to3
# generate server.xml with the following command:
#    openssl req -new -x509 -keyout server.pem -out server.pem -days 365 -nodes
# run as follows:
#    python3 simple-https-server.py
# then in your browser, visit:
#    https://localhost:4443

import http.server, http.server
import ssl
import tempfile
import os

certfile = tempfile.mktemp(suffix='.pem')

os.system('openssl req -new -x509 -subj /CN=localhost -keyout %s -out %s -days 30 -nodes' % (certfile, certfile))
httpd = http.server.HTTPServer(('localhost', 4443), http.server.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket (httpd.socket, certfile=certfile, server_side=True)
print("Listening on localhost:4443")
httpd.serve_forever()
